# Repository Settings Configuration
# This file configures repository settings when the Settings GitHub App is installed
# Install at: https://github.com/apps/settings

repository:
  # Repository description and metadata
  description: "Friday project with comprehensive engineering automation"
  homepage: ""
  topics: []
  
  # Repository features
  has_issues: true
  has_projects: true
  has_wiki: false
  has_pages: false
  has_downloads: true
  
  # Default branch
  default_branch: main
  
  # Allow merge strategies
  allow_squash_merge: true
  allow_merge_commit: false
  allow_rebase_merge: false
  
  # Automatically delete head branches after merge
  delete_branch_on_merge: true
  
  # Enable vulnerability alerts
  enable_vulnerability_alerts: true
  enable_automated_security_fixes: true

# Branch protection rules
branches:
  - name: main
    protection:
      # Require pull request reviews
      required_pull_request_reviews:
        required_approving_review_count: 1
        dismiss_stale_reviews: true
        require_code_owner_reviews: false
        require_last_push_approval: false
      
      # Require status checks
      required_status_checks:
        strict: true
        contexts:
          - build
          - coverage
          - sonar
          - trivy
      
      # Restrictions
      enforce_admins: false
      required_linear_history: false
      allow_force_pushes: false
      allow_deletions: false
      required_conversation_resolution: true
      
      # Require signed commits (optional - uncomment if needed)
      # required_signatures: true

# Labels
labels:
  # Type labels
  - name: bug
    color: d73a4a
    description: Something isn't working
  
  - name: enhancement
    color: a2eeef
    description: New feature or request
  
  - name: feature
    color: 0075ca
    description: New feature
  
  - name: fix
    color: fef2c0
    description: Bug fix
  
  - name: chore
    color: ffc0cb
    description: Maintenance tasks
  
  - name: documentation
    color: 0075ca
    description: Improvements or additions to documentation
  
  # Priority labels
  - name: "priority: low"
    color: 0e8a16
    description: Low priority
  
  - name: "priority: medium"
    color: fbca04
    description: Medium priority
  
  - name: "priority: high"
    color: d93f0b
    description: High priority
  
  - name: "priority: critical"
    color: b60205
    description: Critical priority
  
  # Status labels
  - name: "status: triage"
    color: ededed
    description: Needs triage
  
  - name: "status: in progress"
    color: 0052cc
    description: Work in progress
  
  - name: "status: blocked"
    color: b60205
    description: Blocked by external dependency
  
  - name: "status: ready for review"
    color: 0075ca
    description: Ready for review
  
  # Category labels
  - name: dependencies
    color: 0366d6
    description: Pull requests that update a dependency file
  
  - name: security
    color: b60205
    description: Security related
  
  - name: ci
    color: 000000
    description: Continuous integration
  
  - name: tests
    color: c2e0c6
    description: Testing related
  
  - name: config
    color: d4c5f9
    description: Configuration changes
  
  - name: frontend
    color: 1f883d
    description: Frontend related
  
  - name: backend
    color: 8b5cf6
    description: Backend related
  
  # Special labels
  - name: "good first issue"
    color: 7057ff
    description: Good for newcomers
  
  - name: "help wanted"
    color: 008672
    description: Extra attention is needed
  
  - name: duplicate
    color: cfd3d7
    description: This issue or pull request already exists
  
  - name: invalid
    color: e4e669
    description: This doesn't seem right
  
  - name: question
    color: d876e3
    description: Further information is requested
  
  - name: wontfix
    color: ffffff
    description: This will not be worked on
  
  - name: "skip-changelog"
    color: ededed
    description: Don't include in changelog